

# Лабораторная работа 3.2. Знакомство с NumPy
Библиотека NumPy -- быстрая библиотека для математики в Python, основная структура данных -- массив `numpy.array`:

![](https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif)

In [57]:
# подключение модуля numpy под именем np
import numpy as np

In [58]:
# основная структура данных - массив
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

print("a =", a)
print("b =", b)

a = [1 2 3 4 5]
b = [0.1 0.2 0.3 0.4 0.5]


Создайте массив с 5 любыми числами:

In [59]:
a = np.random.randint(20, size=5)
a

array([ 9,  1, 10,  9,  0])

Арифметические операции, в отличие от операций над списками, применяются поэлементно:

In [60]:
list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

print("list1:", list1)
print('\tlist1 * 3:', list1 * 3)
print('\tlist1 + [1]:', list1 + [1])

print('array1:', array1)
print('\tarray1 * 3:', array1 * 3)
print('\tarray1 + 1:', array1 + 1)

list1: [1, 2, 3]
	list1 * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
	list1 + [1]: [1, 2, 3, 1]
array1: [1 2 3]
	array1 * 3: [3 6 9]
	array1 + 1: [2 3 4]


Создайте массив из 5 чисел. Возведите каждый элемент массива в степень 3

In [61]:
a = np.random.randint(20, size=5)
print(a)
print(a**3)

[ 4  6 18 13 18]
[  64  216 5832 2197 5832]


Если в операции участвуют $2$ массива (по умолчанию -- одинакового размера), операции считаются для соответствующих пар:

In [62]:
print("a + b =", a + b)
print("a * b =", a * b)

a + b = [ 4.1  6.2 18.3 13.4 18.5]
a * b = [0.4 1.2 5.4 5.2 9. ]


In [63]:
# вот это разность
print("a - b =", a - b)

# вот это деление
print("a / b =", a / b)

# вот это целочисленное деление
print("a // b =", a // b)

# вот это квадрат
print("a ** 2 =", a ** 2)

a - b = [ 3.9  5.8 17.7 12.6 17.5]
a / b = [40.  30.  60.  32.5 36. ]
a // b = [39. 29. 60. 32. 36.]
a ** 2 = [ 16  36 324 169 324]


 Создайте два массива одинаковой длины. Выведите массив, полученный делением одного массива на другой.

In [64]:
a = np.random.randint(100, size=5)
print(a)
b = np.random.randint(20, size=5)
print(b)
print(a/b)

[14 62 96 60 33]
[11 15 13 11  7]
[1.27272727 4.13333333 7.38461538 5.45454545 4.71428571]


#### *Л — логика*
К элементам массива можно применять логические операции.

Возвращаемое значение -- массив, содержащий результаты вычислений для каждого элемента (`True` -- "да" или `False` -- "нет"):

In [65]:
print("a =", a)
print("\ta > 1: ", a > 1)
print("\nb =", b)
print("\tb < 0.5:  ", b < 0.5)

print("\nОдновременная проверка условий:")
print("\t(a > 1) & (b < 0.5):  ", (a>1) & (b < 0.5))
print("А вот это проверяет, что a > 1 ИЛИ b < 0.5:  ", (a > 1) | (b < 0.5))

a = [14 62 96 60 33]
	a > 1:  [ True  True  True  True  True]

b = [11 15 13 11  7]
	b < 0.5:   [False False False False False]

Одновременная проверка условий:
	(a > 1) & (b < 0.5):   [False False False False False]
А вот это проверяет, что a > 1 ИЛИ b < 0.5:   [ True  True  True  True  True]


Создайте 2 массива из 5 элементов. Проверьте условие "Элементы первого массива меньше 6, элементы второго массива делятся на 3"

In [66]:
a = np.random.randint(100, size=5)
print(a)
b = np.random.randint(20, size=5)
print(b)

print(a < 6)
print(b % 3 == 0)

[60 10 82 38 95]
[3 2 0 3 3]
[False False False False False]
[ True False  True  True  True]


Теперь проверьте условие "Элементы первого массива делятся на 2 или элементы второго массива больше 2"

In [67]:
print((a % 2 == 0)|(b > 2))

[ True  True  True  True  True]


Зачем это нужно? Чтобы выбирать элементы массива, удовлетворяющие какому-нибудь условию:

In [68]:
print("a =", a)
print("a > 2:", a > 2)
# индексация - выбираем элементы из массива в тех позициях, где True
print("a[a > 2]:", a[a > 2])

a = [60 10 82 38 95]
a > 2: [ True  True  True  True  True]
a[a > 2]: [60 10 82 38 95]


Создайте массив с элементами от 1 до 20. Выведите все элементы, которые больше 5 и не делятся на 2

Подсказка: создать массив можно с помощью функции np.arange(), действие которой аналогично функции range, которую вы уже знаете.

In [69]:
с = np.arange(1,21)
print(с)
print(с[(с > 5) & (с % 2 != 0)])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 7  9 11 13 15 17 19]


#### А ещё NumPy умеет...

Все операции NumPy оптимизированы для быстрых вычислений над целыми массивами чисел и в методах `np.array` реализовано множество функций, которые могут вам понадобиться:

In [70]:
# теперь можно считать средний размер котиков в одну строку!
print("np.mean(a) =", np.mean(a))
# минимальный элемент
print("np.min(a) =", np.min(a))
# индекс минимального элемента
print("np.argmin(a) =", np.argmin(a))
# вывести значения массива без дубликатов
print("np.unique(['male', 'male', 'female', 'female', 'male']) =", np.unique(['male', 'male', 'female', 'female', 'male']))

# и ещё много всяких методов
# Google в помощь

np.mean(a) = 57.0
np.min(a) = 10
np.argmin(a) = 1
np.unique(['male', 'male', 'female', 'female', 'male']) = ['female' 'male']


---

---

Пора еще немного потренироваться с NumPy.

Выполните операции, перечисленные ниже:

In [71]:
print("Разность между a и b:",  a - b
     )
print("Квадраты элементов b:", b ** 2
     )
print("Половины произведений элементов массивов a и b:", a * b
     )

print()
print("Максимальный элемент b:", np.max(b)
     )
print("Сумма элементов массива b:", np.sum(b)
     )
print("Индекс максимального элемента b:", np.argmax(b)
     )

Разность между a и b: [57  8 82 35 92]
Квадраты элементов b: [9 4 0 9 9]
Половины произведений элементов массивов a и b: [180  20   0 114 285]

Максимальный элемент b: 3
Сумма элементов массива b: 11
Индекс максимального элемента b: 0


 Задайте два массива: [5, 2, 3, 12, 4, 5]   и   ['f', 'o', 'o', 'b', 'a', 'r']

Выведите буквы из второго массива, индексы которых соответствуют индексам чисел из первого массива, которые больше 1, меньше 5 и делятся на 2

In [87]:
num = np.array([5, 2, 3, 12, 4, 5])
let = np.array(['f', 'o', 'o', 'b', 'a', 'r'])
print(let[np.where ((num > 1) & (num < 5) & (num % 2 == 0))])

['o' 'a']
