# Лабораторная работа 3.2. Домашнее задание

### Задание №1

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [4]:
import numpy as np

a = np.arange(1,7) * 2
print(a)
b = np.array([7, 11, 15, 18, 23, 29])
print(b)
print((a + b) ** 2)

[ 2  4  6  8 10 12]
[ 7 11 15 18 23 29]
[  81  225  441  676 1089 1681]


$2.$ Выведите все элементы из первого массива, индексы которых соответствуют индексам тех элементов второго массива, которые больше 12 и дают остаток 3 при делении на 5.

In [12]:
print(a[np.logical_and(b > 12, b % 5 == 3)])
print((a % 4 == 0) & (b < 14))

[ 8 10]
[False  True False False False False]


*3.* Проверьте условие "Элементы первого массива делятся на 4, элементы второго массива меньше 14". (Подсказка: в результате должен получиться массив с True и False)

### Задание №2

* Найдите интересный для вас датасет. Например, можно выбрать датасет тут. http://data.un.org/Explorer.aspx (выбираете датасет, жмете на view data, потом download, выбирайте csv формат)
* Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
* Проанализируйте и прокомментируйте содержательно получившиеся результаты
* Все комментарии оформляйте строго в ячейках формата markdown
    

https://www.kaggle.com/datasets/themrityunjaypathak/tesla-stock-price-2005-2023
Цена акций Tesla [2005-2023]

In [18]:
import csv
import numpy as np


# Открытие файла только для чтения
with open('Tesla_stock_Price.csv', 'r', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    # Списки
    Price  = []
    High_price = []
    # Пропуск заголовка
    next(reader)
    # Заполнение списков
    for row in reader:
        if row[3] != '':
            Price.append(float(row[1]))
            High_price.append(float(row[3]))
    Price = np.array(Price)
    High_price = np.array(High_price)
    print(f"Средняя цена акций {np.mean(Price)}, Средняя цена акций из максимальных: {np.mean(High_price)}" )
    print(f"Среднее отклонение цен {np.std(Price)}, среднее отклонение цен из максимальных: {np.std(High_price)}" )
    print(f"Медиана цен  {np.median(Price)}, медиана максимальных цен: {np.median(High_price)}" )
    print(f"Дисперсия цен {np.var(Price)}, дисперсия максимальных цен: {np.var(High_price)}" )

Средняя цена акций 59.68772498426684, Средняя цена акций из максимальных: 61.02593769666456
Среднее отклонение цен 95.57366675624947, среднее отклонение цен из максимальных: 97.80466634694456
Медиана цен  16.325, медиана максимальных цен: 16.56
Дисперсия цен 9134.325777234624, дисперсия максимальных цен: 9565.75275923715
